#############################################
#											#
#	Config file of the ControlPlugin		#
#											#
#############################################
Spawnprotection:
  Block1:
    x: 0
    y: 0
    z: 0
  Block2:
    x: 0
    y: 0
    z: 0
Messages:
  No-permission: You don't have this permission!
  Player-only-command: This is a player-only command!
  Successfully-logged-in: You successfully logged in!
  Successfully-logged-out: You successfully logged out!
  Already-logged-in: You are already logged in!
  Already-logged-out: You are already logged out!