#############################################
#											#
#	Config file of the ControlPlugin		#
#											#
#############################################
Spawnprotection:
  Block1:
    x: 0
    y: 0
    z: 0
  Block2:
    x: 0
    y: 0
    z: 0