name: ControlPlugin
author: Nickitki
main: com.nte.mc.controlplugin.main.Main
version: 1.1.1
commands:
  mcp:
    description: Help command of the ControlPlugin
    permissions: 
    usage: /mcp <args>
  heal:
    description: Heals a Player
    permissions: mcp.health.heal
    usage: /heal [Player]
  setmaxhealth:
    description: Sets max health of a player
    permissions: mcp.health.maxhealth
    usage: /setmaxhealth [<Player, value>] [value]
  speed:
    description: Sets fly or walk speed
    permissions: mcp.mv.speed
    usage: /speed <value>
  fly:
    description: Sets Player flying
    permissions: mcp.mv.fly
    usage: /fly [Player]
  mem:
    description: Shows player current memory usage
    permissions: mcp.mem
    usage: /mem
  inv:
    description: Lets you interact with Inventory of a player
    permissions: mcp.inv
    usage: /inv <Player>
  whois:
    description: Properties of Player
    permissions: mcp.whois
    usage: /whois <Player>
  lag:
    description: Ticks per second statistics
    permissions: mcp.tps
    usage: /tps